"""empty message

Revision ID: 2398e4437a3b
Revises: fc21ead17058
Create Date: 2022-03-02 21:03:34.126720
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2398e4437a3b'
down_revision = 'fc21ead17058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'activities', sa.Column('user_id', postgresql.UUID(), nullable=True)
    )
    op.create_foreign_key(None, 'activities', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_activity_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'activity_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'activity_id',
            postgresql.UUID(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        'users_activity_id_fkey',
        'users',
        'activities',
        ['activity_id'],
        ['id'],
    )
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'user_id')
    # ### end Alembic commands ###
