"""fix: change name tile for title

Revision ID: 72bfecf2c8f6
Revises: 88fb87e0c706
Create Date: 2022-03-04 18:28:15.663639
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '72bfecf2c8f6'
down_revision = '88fb87e0c706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cards', sa.Column('title', sa.String(length=64), nullable=False)
    )
    op.drop_column('cards', 'tile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cards',
        sa.Column(
            'tile', sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
    )
    op.drop_column('cards', 'title')
    # ### end Alembic commands ###
