"""add owner to group

Revision ID: 77c3e4730664
Revises: 49906886c744
Create Date: 2022-03-03 19:19:14.707279
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77c3e4730664'
down_revision = '49906886c744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'groups',
        sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(None, 'groups', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'owner_id')
    # ### end Alembic commands ###
