"""fk na card model

Revision ID: 7e6473bfa46f
Revises: 72bfecf2c8f6
Create Date: 2022-03-04 19:41:23.637566
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e6473bfa46f'
down_revision = '72bfecf2c8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cards',
        sa.Column('activity_id', postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(None, 'cards', 'activities', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'activity_id')
    # ### end Alembic commands ###
