"""empty message

Revision ID: 8c94ed597e82
Revises: c6cbac9cef4a
Create Date: 2022-03-04 14:26:48.658848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c94ed597e82'
down_revision = 'c6cbac9cef4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activities_user_id_fkey', 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key('activities_user_id_fkey', 'activities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
