"""empty message

Revision ID: c6cbac9cef4a
Revises: 77c3e4730664
Create Date: 2022-03-04 14:25:01.822191
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c6cbac9cef4a'
down_revision = '77c3e4730664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'activities_user_id_fkey', 'activities', type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'activities', 'users', ['user_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(
        'activities_user_id_fkey', 'activities', 'users', ['user_id'], ['id']
    )
    # ### end Alembic commands ###
