"""remoçao card.id da activityModel 

Revision ID: faa16575eb00
Revises: 7e6473bfa46f
Create Date: 2022-03-04 19:56:06.982512

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'faa16575eb00'
down_revision = '7e6473bfa46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activities_card_id_fkey', 'activities', type_='foreignkey')
    op.drop_column('activities', 'card_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('card_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('activities_card_id_fkey', 'activities', 'cards', ['card_id'], ['id'])
    # ### end Alembic commands ###
